// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dgfqotxmkkkccxyzoajn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRnZnFvdHhta2trY2N4eXpvYWpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNTA1ODcsImV4cCI6MjA2MjcyNjU4N30.IUFOB3wx0YQjbYm4BNWtmT-P7kfCnCs8To-dv4o9JH0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);